- id: '1604973848959'
  alias: Turn On Christmas Lights at Dark
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:45:00
  - platform: state
    entity_id: binary_sensor.occupied
    to: 'on'
  condition:
  - condition: sun
    after: sunset
    after_offset: -01:00:00
  - condition: state
    entity_id: binary_sensor.occupied
    state: 'on'
  action:
  - type: turn_on
    device_id: 1ee080bf6cfe8f1b778b60fdeee68564
    entity_id: switch.christmas_tree
    domain: switch
  - type: turn_on
    device_id: 7f8f4ff7210eb78288672c2394f4c1af
    entity_id: switch.window_lights
    domain: switch
  mode: single
- id: '1609559449831'
  alias: Morning Routine
  description: ''
  trigger:
  - platform: state
    to: 'off'
    entity_id: input_boolean.night_mode
    from: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.occupied
    state: 'on'
  action:
  - wait_for_trigger:
    - platform: state
      entity_id: binary_sensor.wyze_motion2
      to: 'on'
      from: 'off'
    timeout: 03:00:00
    continue_on_timeout: false
  - data:
      volume_level: 0.8
    service: media_player.volume_set
    target:
      entity_id:
      - media_player.bathroom_echo
      - media_player.kitchen_echo_show
  - service: media_player.play_media
    data:
      entity_id: media_player.bathroom_echo
      media_content_id: amzn1.ask.skill.8e0fbda3-b70c-481d-878f-a2e5e17158c9
      media_content_type: skill
  - wait_for_trigger:
    - platform: state
      entity_id: binary_sensor.wyze_motion3
      to: 'on'
      from: 'off'
    timeout: 01:00:00
    continue_on_timeout: false
  - type: turn_on
    device_id: 4727b2015d290faf287bd1a335620fab
    entity_id: light.kitchen_counter
    domain: light
  - type: turn_on
    device_id: a634fea07a944853cfa4fe710f25fd04
    entity_id: light.kitchen_overhead
    domain: light
  - service: media_player.play_media
    data:
      media_content_id: amzn1.ask.skill.8e0fbda3-b70c-481d-878f-a2e5e17158c9
      media_content_type: skill
    target:
      entity_id:
      - media_player.kitchen_echo_show
  - service: media_player.media_stop
    target:
      entity_id: media_player.bathroom_echo
  - wait_for_trigger:
    - platform: template
      value_template: "{{\n  is_state('person.sarah', 'away') \n  and is_state('input_boolean.wfh',\
        \ 'on')\n  and is_state('binary_sensor.office_door', 'on')\n  and is_state('binary_sensor.public_space_motion',\
        \ 'off')\n}}"
    timeout: 01:00:00
  - service: light.turn_off
    data: {}
    entity_id: light.bedroom
  - service: media_player.media_stop
    target:
      entity_id: media_player.kitchen_echo_show
  mode: single
- id: '1619291764637'
  alias: Motion -- Side Door
  description: ''
  use_blueprint:
    path: networkingcat/yet_another_motion_automation.yaml
    input:
      time_scene_night: 0:00:00
      motion_entity: binary_sensor.side_door_motion
      light_target:
        entity_id:
        - light.side_porch
        - light.laundry_room
      elevation_check: 10
      time_scene_evening: 0:00:00
      time_scene_day: 0:00:00
      time_scene_morning: 0:00:00
      automation_blocker: input_boolean.outside_motion_lights
      time_scene_ambient_end: 0:00:00
      automation_blocker_boolean: true
- id: '1619296919322'
  alias: Dimmer -- Office
  description: ''
  use_blueprint:
    path: bjpetit/zha_lutron_aurora_blueprint.yaml
    input:
      remote: a01dd1e3ea560f4fb0afcf5354493abb
      light:
        area_id: a78dc9b8222b47eebe4561988e57b0b0
- id: '1619298602418'
  alias: Dimmer -- Guest Bedroom
  description: ''
  use_blueprint:
    path: bjpetit/zha_lutron_aurora_blueprint.yaml
    input:
      remote: 224e0e9a1113cc16236212cc415e37e2
      light:
        area_id: 78d9e7596f014179b37ca4129fcb9a68
- id: '1619298756428'
  alias: Dimmer -- Guest Bathroom
  description: ''
  use_blueprint:
    path: bjpetit/zha_lutron_aurora_blueprint.yaml
    input:
      remote: a6c46ea29be9e854e67b05d5ca0d01fc
      light:
        area_id: 5972569ba2994df483c55163a2d8fd2a
- id: '1619298991377'
  alias: Dimmer -- Living Room
  description: ''
  use_blueprint:
    path: bjpetit/zha_lutron_aurora_blueprint.yaml
    input:
      remote: 9ebcf9676a38312a754423049e5ef143
      light:
        area_id: 87c768ba445d4b398f17ec723dc54377
- id: '1619299286679'
  alias: Dimmer -- Dining Room
  description: ''
  use_blueprint:
    path: bjpetit/zha_lutron_aurora_blueprint.yaml
    input:
      remote: 43c144534af08ead226fb0b11c2ab85b
      light:
        entity_id: light.dining_room_ceiling
- id: '1619299919120'
  alias: Dimmer -- Bedroom
  description: ''
  use_blueprint:
    path: bjpetit/zha_lutron_aurora_blueprint.yaml
    input:
      remote: e765caaa40236417c67b4aebc0c1a8ac
      light:
        area_id: b2672f722c53428e92427703040fb764
- id: '1619300410823'
  alias: Dimmer -- Bathroom
  description: ''
  use_blueprint:
    path: bjpetit/zha_lutron_aurora_blueprint.yaml
    input:
      remote: f0a96177eb7693b52288825ef15218bd
      light:
        entity_id: light.bathroom
- id: '1620251075858'
  alias: Send Unlock Notification When Coming Home
  description: ''
  use_blueprint:
    path: Martinnygaard/actionable-notifications-for-android-when-entering-or-leaving-a-zone.yaml
    input:
      notify_device: 58748fca30234e8a822e3b1600d14200
      trigger_entity: person.nathan
      trigger_event: enter
      trigger_zone: zone.home
      notification_title: Unlock Door?
      action_1_title: Unlock
      first_action:
      - service: lock.unlock
        target:
          entity_id: lock.back_door_lock
      action_2_title: Lock
      second_action:
      - service: lock.lock
        target:
          entity_id: lock.back_door_lock
- id: '1620332636293'
  alias: Low battery level detection & notification for all battery sensors
  description: ''
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      exclude:
        entity_id:
        - sensor.iphone_battery_state
        - sensor.iphone_battery_level
        - sensor.nathan_s_pixel_battery_level
        - sensor.pixel_4_battery_state
        - sensor.rooben_battery_level
      actions:
      - service: script.notify_sarah_and_nathan
        data:
          message: Battery is Dying
          url: /lovelace/data
          more_info: The battery is dying for {{ sensors }}
- id: '1620357325146'
  alias: Motion -- Back Yard
  description: ''
  use_blueprint:
    path: networkingcat/yet_another_motion_automation.yaml
    input:
      time_scene_night: 0:00:00
      motion_entity: binary_sensor.back_yard
      elevation_check: 10
      time_scene_evening: 0:00:00
      time_scene_day: 0:00:00
      time_scene_morning: 0:00:00
      time_scene_ambient_end: 0:00:00
      time_scene_ambient_start: 0:00:00
      automation_blocker: input_boolean.outside_motion_lights
      light_target:
        entity_id: light.back_porch
      automation_blocker_boolean: true
- id: '1620360426386'
  alias: Alarm -- Trigger when Armed Away
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.public_space_motion
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: binary_sensor.wyze_motion1
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: binary_sensor.wyze_motion2
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: binary_sensor.back_door_the_current_status_of_the_door
    from: 'on'
    to: 'off'
  condition:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: armed_away
  action:
  - service: alarm_control_panel.alarm_trigger
    target:
      entity_id: alarm_control_panel.home_alarm
  mode: single
- id: alexa_media_player_authentication_required
  alias: Alexa Media Player Authentication Required
  trigger:
    platform: event
    event_type: alexa_media_relogin_required
  condition: []
  action:
  - service: notify.mobile_app_pixel_4
    data:
      title: Alexa Media Player Integration
      message: 🔑 Authentication Required
- id: '1620443082110'
  alias: Alarm -- Run Alarm when Triggered
  description: ''
  trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: triggered
  condition: []
  action:
  - service: script.notify_sarah_and_nathan
    data:
      message: Intruder Alert
      more_info: The house alarm is going off
  - service: media_player.volume_set
    target:
      device_id: 28e026b391880a6a90ba262b30514dcc
    data:
      volume_level: 1
  - service: notify.alexa_media
    data:
      data:
        type: tts
      target: group.alexa_everywhere
      message: Alarm will sound in 10 seconds
  - delay:
      hours: 0
      minutes: 0
      seconds: 14
      milliseconds: 0
  - condition: not
    conditions:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: disarmed
  - service: media_player.volume_set
    data:
      volume_level: 1
    target:
      entity_id: media_player.everywhere
  - service: script.turn_on
    target:
      entity_id:
      - script.alarm_flash_while_triggered
      - script.alarm_beep_while_triggered
  mode: single
- id: '1621301311010'
  alias: Motion -- Front Door
  description: ''
  use_blueprint:
    path: networkingcat/yet_another_motion_automation.yaml
    input:
      time_scene_night: 0:00:00
      motion_entity: binary_sensor.front_door_motion
      time_scene_evening: 0:00:00
      time_scene_day: 0:00:00
      light_target:
        entity_id:
        - light.front_porch
      time_scene_morning: 0:00:00
      time_scene_ambient_end: 0:00:00
      automation_blocker: input_boolean.outside_motion_lights
      time_scene_ambient_start: 0:00:00
      automation_blocker_boolean: true
- id: '1621799711823'
  alias: Motion -- Mudroom
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.mudroom_camera
    to: 'on'
  condition: []
  action:
  - service: notify.mobile_app_iphone
    data:
      title: The Cat is Eating
      message: Check Wyze for camera feed
  mode: single
