- id: '1586306345598'
  alias: Turn Off Fans When Cold
  description: Turn off the fans if the temperature drops below 40 and we're in bed
  trigger:
  - below: '60'
    entity_id: weather.home
    platform: numeric_state
    value_template: '{{ state.attributes.temperature }}'
  condition:
  - after: sunset
    before: sunrise
    before_offset: '+3:00:00'
    condition: sun
  action:
  - data: {}
    entity_id: group.fans
    service: homeassistant.turn_off
- id: '1586661602545'
  alias: Turn On Master Bedroom Before Bed
  description: ''
  trigger:
  - at: '21:00'
    platform: time
  condition:
  - condition: state
    entity_id: group.master_room_people
    state: home
  action:
  - data:
      group_name: Nathan's Room
      scene_name: Bedtime
    service: hue.hue_activate_scene
- id: '1586735161292'
  alias: Turn Off Everything When Everyone Leaves
  description: ''
  trigger:
  - entity_id: binary_sensor.occupied
    for: 00:05:00
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: group.all_lights
    service: homeassistant.turn_off
  - data: {}
    entity_id: media_player.living_room_tv
    service: media_player.turn_off
  - data:
      entity_id: alarm_control_panel.alexa_guard_ee9c2
    service: alarm_control_panel.alarm_arm_away
  - data: {}
    entity_id: vacuum.rooben
    service: vacuum.start
- id: '1586735596195'
  alias: Turn Off Master Bedroom When We Leave
  description: ''
  trigger:
  - entity_id: binary_sensor.are_master_bedroom_people_home
    for: 00:05:00
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: group.master_bedroom
    service: homeassistant.turn_off
- id: '1586737651295'
  alias: Toggle Automations When There Are Visitors
  description: ''
  trigger:
  - entity_id: input_boolean.visitors
    platform: state
  condition: []
  action:
  - entity_id: group.visitor_automations
    service_template: "{% if is_state('input_boolean.visitors', 'on') %}\n  homeassistant.turn_off\n\
      {% else %}\n  homeassistant.turn_on\n{% endif %}"
- id: '1587162726799'
  alias: First Person Home
  description: ''
  trigger:
  - entity_id: binary_sensor.occupied
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: alarm_control_panel.alexa_guard_ee9c2
    service: alarm_control_panel.alarm_disarm
  - data: {}
    entity_id: vacuum.rooben
    service: vacuum.stop
  - wait_template: '{{ is_state(''vacuum.rooben'', ''off'') }}'
  - data: {}
    entity_id: vacuum.rooben
    service: vacuum.return_to_base
- id: '1587250642749'
  alias: Notify that Kane is Home
  description: ''
  trigger:
  - entity_id: person.kane
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: group.master_room_people
    state: home
  - condition: state
    entity_id: binary_sensor.everyone_in_bed
    state: 'off'
  action:
  - data:
      message: Kane's home
    service: script.notify_sarah_and_nathan
- id: '1587255222033'
  alias: Run Roomba Every Morning
  description: ''
  trigger:
  - at: 05:00:00
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: vacuum.rooben
    service: vacuum.start
- id: '1587264300585'
  alias: Calendar Alarm Sync
  description: ''
  trigger:
  - platform: template
    value_template: '{{state_attr(''calendar.alarm'', ''offset_reached'')}}'
  condition:
  - condition: state
    entity_id: group.master_room_people
    state: home
  action:
  - data: {}
    service: script.slow_alarm
- id: '1587273614675'
  alias: Calendar Toggles Visitors
  description: ''
  trigger:
  - entity_id: calendar.visitors
    platform: state
  condition: []
  action:
  - entity_id: input_boolean.visitors
    service_template: "{% if is_state('calendar.visitors', 'on') %}\n  input_boolean.turn_on\n\
      {% else %}\n  input_boolean.turn_off\n{% endif %}"
- id: '1587438080867'
  alias: Turn On Kitchen if Motion
  description: ''
  trigger:
  - entity_id: binary_sensor.kitchen_motion
    platform: state
    to: 'on'
  condition:
  - condition: template
    value_template: '{{ now() | as_timestamp - states.group.kitchen_lights.last_changed
      | as_timestamp > 30 }}'
  action:
  - data: {}
    entity_id: group.kitchen_lights
    service: homeassistant.turn_on
- id: '1587438080868'
  alias: Turn Off Kitchen After No Motion
  description: ''
  trigger:
  - entity_id: binary_sensor.kitchen_motion
    for: 0:05:00
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: group.kitchen_lights
    service: homeassistant.turn_off
- id: '1587443561409'
  alias: Notify of Intruder
  description: ''
  trigger:
  - entity_id: binary_sensor.kitchen_motion
    platform: state
    to: 'on'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: alarm_control_panel.alexa_guard_ee9c2
      state: armed_away
    - condition: state
      entity_id: binary_sensor.occupied
      state: 'off'
  action:
  - data:
      message: Motion Detected in Living Room
      title: Hide Yo Kids, Hide Yo Wife!
    service: notify.notify
- id: '1587483555425'
  alias: Set Theme at Startup
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      name: Google Dark Theme
    service: frontend.set_theme
- id: '1587609505669'
  alias: Doing Laundry Turns on Hallway
  description: ''
  trigger:
  - entity_id: binary_sensor.wyze_door2
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: var.hallway_before_laundry_opened
    service: var.update
  - brightness_pct: 100
    device_id: 57e3a993d8284b209bafe15a45bf0f97
    domain: light
    entity_id: light.hallway_1
    type: turn_on
  - brightness_pct: 100
    device_id: ff6565ddb6cb46e88cd63742819aae83
    domain: light
    entity_id: light.hallway_2
    type: turn_on
- id: '1587612663415'
  alias: Close Laundry Door Resets Lights
  description: ''
  trigger:
  - entity_id: binary_sensor.wyze_door2
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: var.hallway_before_laundry_opened
    state: 'False'
  action:
  - data:
      entity_id: group.hallway
      transition: 6
    service: light.turn_off
- id: '1587614908680'
  alias: Notify If Bedroom Door Changes When We're Away
  description: ''
  trigger:
  - entity_id: binary_sensor.wyze_door1
    platform: state
    to: 'off'
  - entity_id: binary_sensor.wyze_door1
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: group.master_room_people
    state: not_home
  action:
  - data:
      message: The bedroom door was {% if is_state('binary_sensor.wyze_door1', 'on')
        %}opened{% else %}closed{% endif %}!
      title: Someone is in your room
    service: notify.mobile_app_iphone
  - data:
      message: The bedroom door was {% if is_state('binary_sensor.wyze_door1', 'on')
        %}opened{% else %}closed{% endif %}!
      title: Someone is in your room
    service: notify.mobile_app_pixel_4
- id: '1587668411958'
  alias: Calendar Toggles WFH
  description: ''
  trigger:
  - entity_id: binary_sensor.is_during_workday
    platform: state
  condition:
  - condition: state
    entity_id: calendar.wfh
    state: 'on'
  action:
  - entity_id: input_boolean.wfh
    service_template: "{% if is_state('binary_sensor.is_during_workday', 'on') %}\n\
      \  input_boolean.turn_on\n{% else %}\n  input_boolean.turn_off\n{% endif %}"
- id: '1587673304305'
  alias: Turn On Kitchen When Leaving Bedroom
  description: ''
  trigger:
  - entity_id: binary_sensor.wyze_door1
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: group.kitchen_lights
    service: switch.turn_on
- id: '1587673576123'
  alias: Toggle Automations When WFH
  description: ''
  trigger:
  - entity_id: input_boolean.wfh
    platform: state
  condition: []
  action:
  - entity_id: group.wfh_automations
    service_template: "{% if is_state('input_boolean.wfh', 'on') %}\n  homeassistant.turn_on\n\
      {% else %}\n  homeassistant.turn_off\n{% endif %}"
- id: '1587677710011'
  alias: Toggle Night Automations
  description: ''
  trigger:
  - entity_id: input_boolean.night_mode
    platform: state
  condition: []
  action:
  - entity_id: group.bedtime_automations
    service_template: "{% if is_state('input_boolean.night_mode', 'on') %}\n  homeassistant.turn_on\n\
      {% else %}\n  homeassistant.turn_off\n{% endif %}"
- id: '1587852659451'
  alias: Tv Night Scenes
  description: Turns on the appropriate living room scenes when the tv is playing
    at night
  trigger:
  - entity_id: sun.sun
    platform: state
    to: below_horizon
  - entity_id: media_player.living_room_tv
    for: 00:00:10
    platform: state
    to: playing
  - entity_id: media_player.living_room_tv
    platform: state
    to: paused
  - entity_id: media_player.living_room_tv
    for: 00:00:22
    platform: state
    to: standby
  - entity_id: media_player.living_room_tv
    platform: state
    to: 'off'
  condition:
  - condition: or
    conditions:
    - after: sunset
      condition: sun
    - before: sunrise
      condition: sun
  - condition: state
    entity_id: binary_sensor.occupied
    state: 'on'
  - condition: state
    entity_id: input_boolean.night_mode
    state: 'off'
  - condition: template
    value_template: '{{ trigger.from_state.state != "unavailable" }}'
  action:
  - data_template:
      entity_id: "{% if is_state_attr('media_player.living_room_tv', 'app_id', 'com.hulu.plus')\
        \ %}\n  {% if is_state('media_player.living_room_tv', 'paused') %}\n    scene.tv_playing_at_night\n\
        \  {% elif is_state('media_player.living_room_tv', 'standby') %}\n    scene.tv_paused_at_night\n\
        \  {% endif %}\n{% else %}\n  {% if is_state('media_player.living_room_tv',\
        \ 'playing') %}\n    scene.tv_playing_at_night\n  {% elif is_state('media_player.living_room_tv',\
        \ 'standby')\n     or is_state('media_player.living_room_tv', 'paused')\n\
        \  %}\n    scene.tv_paused_at_night\n  {% else %}\n    scene.tv_off_at_night\n\
        \  {% endif %}\n{% endif %}\n"
    service: scene.turn_on
- id: '1587854965958'
  alias: Turn Off Kane's Bedroom When He Leaves
  description: ''
  trigger:
  - entity_id: person.kane
    for: 00:05:00
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - data: {}
    entity_id: light.kane_s_nightstand, light.top_lamp, light.bottom_lamp
    service: light.turn_off
- id: '1587996987502'
  alias: Turn Off Public Devices When Night Mode Turns On
  description: ''
  trigger:
  - entity_id: input_boolean.night_mode
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: group.public_lights
    service: homeassistant.turn_off
  - data: {}
    entity_id: media_player.living_room_tv
    service: media_player.turn_off
- id: '1588639275094'
  alias: Toggle Night Mode
  description: ''
  trigger:
  - entity_id: binary_sensor.everyone_in_bed
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: calendar.alarm
    from: 'off'
    platform: state
    to: 'on'
  - platform: template
    value_template: '{{ states(''sensor.time'') == states(''input_datetime.morning'')
      }}'
  condition:
  - condition: state
    entity_id: input_boolean.visitors
    state: 'off'
  action:
  - entity_id: input_boolean.night_mode
    service_template: "{% if trigger.entity_id == 'binary_sensor.everyone_in_bed'\
      \ %}\n  input_boolean.turn_on\n{% else %}\n  input_boolean.turn_off\n{% endif\
      \ %}"
- id: '1589240357141'
  alias: Turn Off Public Lights After No Motion
  description: ''
  trigger:
  - entity_id: binary_sensor.public_space_motion
    for: 0:05:00
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: group.public_lights
    service: homeassistant.turn_off
