- id: '1604973848959'
  alias: Turn On Christmas Lights at Dark
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:45:00
  - platform: state
    entity_id: binary_sensor.occupied
    to: 'on'
  condition:
  - condition: sun
    after: sunset
    after_offset: -01:00:00
  - condition: state
    entity_id: binary_sensor.occupied
    state: 'on'
  action:
  - type: turn_on
    device_id: 1ee080bf6cfe8f1b778b60fdeee68564
    entity_id: switch.christmas_tree
    domain: switch
  - type: turn_on
    device_id: 7f8f4ff7210eb78288672c2394f4c1af
    entity_id: switch.window_lights
    domain: switch
  mode: single
