- id: '1590193462462'
  alias: Notify Rooben's Bin is Full
  description: ''
  trigger:
  - entity_id: binary_sensor.rooben_bin_full
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: It's your turn to empty it 🚮
      title: Rooben's Bin is Full
    service: script.notify_random
