
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate
homeassistant:
  customize: !include customize.yaml
group: !include_dir_merge_named ./groups
automation: !include automations.yaml
automation old: !include_dir_merge_list ./automations
script: !include scripts.yaml
scene: !include scenes.yaml
frontend:
  themes: !include_dir_merge_named ./themes

http:
  server_port: 80

media_player: !include_dir_merge_list ./media_players

device_tracker: !include ./devices_to_track.yaml

binary_sensor:
  - platform: template
    sensors: !include sensors/template_binary_sensors.yaml

  - platform: wyzesense
    device: auto

sensor: !include_dir_merge_list ./sensors

tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: "1"
  platform: smart_life

# light:
#   - platform: flux_led
#     devices:
#       192.168.87.186:
#         name: Kitchen String Lights

google:
  client_id: !secret google_cal_client_id
  client_secret: !secret google_cal_client_secret

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  project_id: !secret nest_project_id
  subscriber_id: !secret nest_subscriber_id

var: !include variables.yaml

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
  
recorder:
  exclude:
    entities:
      - sensor.date_time_iso
      - sensor.time
      - sensor.timestamp

alexa_media:
  accounts:
    - email: !secret amazon_email
      password: !secret amazon_password
      url: amazon.com

camera:
  - platform: local_file
    file_path: /config/www/mail_and_packages/mail_today.gif
    name: mail_usps

switch:
  - platform: switchmate
    mac: 'f3:7e:9f:7b:3e:95'
  - platform: switchmate
    mac: 'f7:37:b9:d5:53:23'
  - platform: template
    switches: !include switches/template_switches.yaml
    