# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate
homeassistant:
  customize: !include customize.yaml
group: !include_dir_merge_named ./groups
automation: !include automations.yaml
automation old: !include_dir_merge_list ./automations
script: !include scripts.yaml
scene: !include scenes.yaml
frontend:
  themes: !include_dir_merge_named ./themes

http:
  server_port: 80

media_player: !include_dir_merge_list ./media_players

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key
  country: US #optional, added in 3.6.24

device_tracker: !include ./devices_to_track.yaml

binary_sensor:
  - platform: template
    sensors: !include sensors/template_binary_sensors.yaml

  - platform: wyzesense
    device: auto

sensor: !include_dir_merge_list ./sensors

template:
  - sensor:
    - name: Number of People at Home
      unique_id: 'number_of_people_at_home'
      state: >-
        {{ dict((states.person)|groupby('state'))['home']|count }}
  - sensor:
    - name: Last Number of People at Home
      unique_id: 'last_number_of_people_at_home'
      state: >-
        {{ trigger.from_state.state }}
    trigger:
    - platform: state
      entity_id: sensor.number_of_people_at_home
  - binary_sensor:
    - name: Back Yard Floodlight Motion
      state: >-
        {{states("input_boolean.alexa_back_yard_floodlight_motion")}}
      device_class: motion
  - binary_sensor:
    - name: Parking Pad Floodlight Motion
      state: >-
        {{states("input_boolean.alexa_parking_pad_floodlight_motion")}}
      device_class: motion

light:
  - platform: flux_led
    devices:
      192.168.1.48:
        name: Under Desk Lights
  - platform: switch
    name: String Lights
    entity_id: switch.string_lights
  - platform: switch
    name: BL1
    entity_id: switch.bl1
  - platform: switch
    name: BL2
    entity_id: switch.bl2
  - platform: group
    name: Dining Room Ceiling
    entities:
      - light.drc1
      - light.drc2
  - platform: switch
    name: g1
    entity_id: switch.g1
  - platform: switch
    name: g2
    entity_id: switch.g2
  - platform: group
    name: Garland
    entities:
      - light.g1
      - light.g2
  - platform: group
    name: Basement Lights
    entities:
      - light.bl1
      - light.bl2
# Alexa routines don't support light toggle as a trigger. yet?
#  - platform: template
#    lights:
#      back_yard_floodlight:
#        friendly_name: Back Yard Floodlight
#        value_template: >-
#          {{states("input_boolean.alexa_back_yard_floodlight")}}
#        turn_off:
#          service: input_boolean.turn_off
#          entity_id: input_boolean.alexa_back_yard_floodlight
#        turn_on:
#          service: input_boolean.turn_on
#          entity_id: input_boolean.alexa_back_yard_floodlight
#      parking_pad_floodlight:
#        friendly_name: Parking Pad Floodlight
#        value_template: >-
#          {{states("input_boolean.alexa_parking_pad_floodlight")}}
#        turn_off:
#          service: input_boolean.turn_off
#          entity_id: input_boolean.alexa_parking_pad_floodlight
#        turn_on:
#          service: input_boolean.turn_on
#          entity_id: input_boolean.alexa_parking_pad_floodlight
        

google:
  client_id: !secret google_cal_client_id
  client_secret: !secret google_cal_client_secret

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  project_id: !secret nest_project_id
  subscriber_id: !secret nest_subscriber_id

var: !include variables.yaml

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
  
recorder:
  exclude:
    entities:
      - sensor.date_time_iso
      - sensor.time
      - sensor.timestamp

alexa_media:
  accounts:
    - email: !secret amazon_email
      password: !secret amazon_password
      url: amazon.com

wyzeapi:
  username: !secret wyze_username
  password: !secret wyze_password
  sensors: false

switch:
  # - platform: switchmate
  #   mac: 'f3:7e:9f:7b:3e:95'
  # - platform: switchmate
  #   mac: 'f7:37:b9:d5:53:23'
  - platform: template
    switches: !include switches/template_switches.yaml
  - platform: wake_on_lan
    mac: !secret nathan_pc_mac
    name: "Tater_PC"
    host: !secret nathan_pc_ip
    broadcast_address: !secret nathan_pc_ip

roomba:
  - host: !secret roomba_host
    blid: !secret roomba_blid
    password: !secret roomba_password

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret alarm_code
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0

rest_command: !include rest_commands.yaml

camera: !include cameras.yaml
image_processing: !include image_processing.yaml

proximity:
  home:
    ignored_zones:
      - zone.project_access
      - zone.osi
    devices:
      - person.nathan
      - person.sarah
    tolerance: 100
    unit_of_measurement: mi
