- platform: switch
  name: String Lights
  entity_id: switch.string_lights
- platform: switch
  name: BL1
  entity_id: switch.bl1
- platform: switch
  name: BL2
  entity_id: switch.bl2
- platform: switch
  name: g1
  entity_id: switch.g1
- platform: switch
  name: g2
  entity_id: switch.g2
- platform: group
  name: Garland
  entities:
    - light.g1
    - light.g2
# Alexa routines don't support light toggle as a trigger. yet?
#  - platform: template
#    lights:
#      back_yard_floodlight:
#        friendly_name: Back Yard Floodlight
#        value_template: >-
#          {{states("input_boolean.alexa_back_yard_floodlight")}}
#        turn_off:
#          service: input_boolean.turn_off
#          entity_id: input_boolean.alexa_back_yard_floodlight
#        turn_on:
#          service: input_boolean.turn_on
#          entity_id: input_boolean.alexa_back_yard_floodlight
#      parking_pad_floodlight:
#        friendly_name: Parking Pad Floodlight
#        value_template: >-
#          {{states("input_boolean.alexa_parking_pad_floodlight")}}
#        turn_off:
#          service: input_boolean.turn_off
#          entity_id: input_boolean.alexa_parking_pad_floodlight
#        turn_on:
#          service: input_boolean.turn_on
#          entity_id: input_boolean.alexa_parking_pad_floodlight
        
