blueprint:
  name: Notifications for when lights are left on for too long
  description: If any lights are left on longer than the specified period, then run an action.
  domain: automation
  input:
    time_in_hours:
      name: Allowed on Duration in Hours
      description: The length of time a light is allowed to be on before the action is run.
      default: 2
      selector:
        number:
          min: .01
          max: 168
          step: .1
          mode: slider
          unit_of_measurement: hours
    exclude:
      name: Excluded Entities
      description: Light entities to exclude from detection. Only
        entities are supported, devices must be expanded!
      default:
        entity_id: []
      selector:
        target:
          entity:
            device_class: light
    actions:
      name: Actions
      description: Notifications or similar to be run. {{lights}} is replaced with
        the names of light entities that have been on for longer than the period.
      selector:
        action:
    check_interval:
      name: Check Interval
      description: How often, in minutes, to check if the lights have been left on
      default: 1
      selector:
        number:
          min: 1
          max: 3600
          mode: slider
          unit_of_measurement: minutes
variables:
  exclude: !input 'exclude'
  time_in_hours: !input 'time_in_hours'
  input_interval: !input 'check_interval'
  time_pattern_input: '/{{input_interval}}'
  lights: >-
    {% set result = namespace(lights=[]) %}
    {%- for state in states.light -%}
      {%- if state.state == 'on'
          and state.last_changed | as_timestamp < now() | as_timestamp - 60 * 60 * time_in_hours
          and not state.entity_id in exclude.entity_id
      -%}
          {% set result.lights = result.lights + [state.name] %}
      {%- endif -%}
    {%- endfor -%}
    {{ result.lights | join(', ') }}
trigger:
  - platform: time_pattern
    minutes: '/5'
condition:
- '{{ lights != '''' }}'
action:
- choose: []
  default: !input 'actions'
mode: single
