visitor_automations:
  name: Visitor Un-friendly Automations
  entities:
    - automation.turn_off_everything_when_people_leave
    - automation.turn_off_master_bedroom_when_we_leave
    - automation.run_roomba_every_morning # This is turned on while we have the vacuum in the guest bedroom. If we move it back to the living room, we can remove this line.
