- platform: history_stats
  name: Quarantine Meter Nathan
  entity_id: person.nathan
  state: "home"
  type: ratio
  duration:
    days: 10
  end: "{{ now() }}"

- platform: history_stats
  name: Quarantine Meter Sarah
  entity_id: person.sarah
  state: "home"
  type: ratio
  duration:
    days: 10
  end: "{{ now() }}"

- platform: history_stats
  name: Quarantine Meter Times Nathan Left
  entity_id: person.nathan
  state: "home"
  type: count
  duration:
    days: 10
  end: "{{ now() }}"

- platform: history_stats
  name: Quarantine Meter Times Sarah Left
  entity_id: person.sarah
  state: "home"
  type: count
  duration:
    days: 10
  end: "{{ now() }}"
