- platform: time_date
  display_options:
    - "time"
    - "date_time_iso"

- platform: template
  sensors:
    timestamp:
      value_template: >-
        {{ states('sensor.date_time_iso') and now() | as_timestamp }}
