- platform: time_date
  display_options:
    - "time"
    - "date_time_iso"

- platform: template
  sensors:
    timestamp:
      entity_id: sensor.date_time_iso
      value_template: >-
        {{ now() | as_timestamp }}
