- platform: time_date
  display_options:
    - "time"
    - "date_time_iso"

- platform: template
  sensors:
    timestamp:
      value_template: >-
        {{ (strptime(states('sensor.date_time_iso'), '%Y-%m-%dT%H:%M:%S%z')) | as_timestamp }}
