- platform: androidtv
  name: Living Room TV
  host: 192.168.1.50
  state_detection_rules:
    "com.amazon.tv.launcher":
      - "standby"
    "com.amazon.tv.inputpreference.service":
      - "playing"
    "com.hulu.plus":
      - "playing":
          "wake_lock_size": 2 # this indentation is important!
      - "paused":
          "wake_lock_size": 0 # this indentation is important!
      - "standby"
    "com.amazon.avod":
      - "media_session_state"

- platform: androidtv
  name: Bedroom TV
  host: 192.168.1.27
  state_detection_rules:
    "com.amazon.tv.launcher":
      - "standby"
    "com.amazon.tv.inputpreference.service":
      - "playing"
    "com.hulu.plus":
      - "playing":
          "wake_lock_size": 2 # this indentation is important!
      - "paused":
          "wake_lock_size": 0 # this indentation is important!
      - "standby"
    "com.amazon.avod":
      - "media_session_state"
