esphome:
  name: bathroom
  platform: ESP32
  board: esp32dev
  includes:
    - dht20.h

substitutions:
  refresh_rate: '30' #seconds

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bathroom Fallback Hotspot"
    password: !secret ap_password

captive_portal:

i2c:
  sda: 21
  scl: 22
  scan: true
  id: dht20
  
sensor:
- platform: custom
  lambda: |-
    auto dht = new DHT20($refresh_rate * 1000);
    App.register_component(dht);
    return {dht->temperature_sensor, dht->humidity_sensor};
  sensors:
  - name: "Bathroom Temperature"
    unit_of_measurement: °C
    accuracy_decimals: 1
  - name: "Bathroom Humidity"
    unit_of_measurement: '%'
    accuracy_decimals: 1