esphome:
  name: bedroom-fireplace-thermostat
  platform: ESP8266
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bedroom-Fireplace-Thermostat"
    password: !secret ap_password

captive_portal:

sensor:
  - platform: dht
    pin: D0
    temperature:
      name: "Bedroom Temperature"
      id: bedroom_temperature
    humidity:
      name: "Bedroom Humidity"
      id: bedroom_humidity
    model: DHT11
    update_interval: 60s
    
switch:
  - platform: gpio
    name: "Bedroom Fireplace"
    id: bedroom_fireplace
    pin:
      number: D1
    internal: true
    
climate:
  - platform: thermostat
    name: "Bedroom Thermostat"
    sensor: bedroom_temperature
    default_target_temperature_low: 65 °F
    min_heating_off_time: 30s
    min_heating_run_time: 30s
    min_idle_time: 30s
    heat_action:
      - switch.turn_on: bedroom_fireplace
    idle_action:
      - switch.turn_off: bedroom_fireplace
    startup_delay: true
