esphome:
  name: grow-room
  platform: ESP32
  board: esp32dev
    
substitutions:
  refresh_rate: 30s
  vin: '3.3' # Used to calculate lux. 3.3 Since that's the vcc pin it's pulling from.
  r: '10000' # Resistance of reistor used with photoresistor.

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "a459fa15575c513e6380b09bc0673ee8"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Grow-Room Fallback Hotspot"
    password: "T62vJ1D6AX5W"

captive_portal:

i2c:
  sda: 21
  scl: 22
  scan: true

sensor:
  - platform: aht10
    temperature:
        name: "Growroom Temperature"
        unit_of_measurement: °C
        accuracy_decimals: 1
        device_class: temperature
    humidity:
      name: "Growroom Humidity"
      unit_of_measurement: '%'
      accuracy_decimals: 1
      device_class: humidity
    update_interval: $refresh_rate

  - platform: adc
    pin: 32
    name: "Grow Room Brightness"
    update_interval: 30s
    attenuation: auto
    device_class: illuminance
    unit_of_measurement: lm
    accuracy_decimals: 1
    filters:
      - lambda: return 500 / (($r * ($vin - x) / x) / 1000);