esphome:
  name: smart-button
  on_shutdown:
    then:
      - light.turn_off: smart_light
  on_boot:
    then:
      - light.turn_on:
          id: smart_light
          effect: none

esp32:
  board: esp32dev

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Smart-Button Fallback Hotspot"
    password: !secret ap_password

captive_portal:

deep_sleep:
  id: ds
  run_duration: 10s
  wakeup_pin: 
    number: 14
    inverted: True
  # wakeup_pin_mode: KEEP_AWAKE

binary_sensor:
  - platform: gpio
    id: smart_button
    pin:
      number: 14
      mode: INPUT_PULLUP
      inverted: True
    name: "Smart Button"
    on_click:
      max_length: 1000ms
      then:
        - light.toggle:
            id: smart_light
      
    # Allow OTA Updates
    on_multi_click:
    - timing:
        - ON for at least 10s
      then:
        - logger.log: "Waiting for OTA update"
        - deep_sleep.prevent: ds
        - light.turn_on:
            id: smart_light
            effect: Fast Pulse
        - delay: 3min
        - light.turn_off:
            id: smart_light
        - deep_sleep.enter: ds

light:
  - platform: monochromatic
    name: "Smart Button Light"
    id: smart_light
    output: light_output
    effects:
      - pulse:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
      - pulse:
          name: "Slow Pulse"
          update_interval: 2s        


output:
  - platform: ledc
    pin: 13
    id: light_output
