esphome:
  name: weather-station-1
  platform: ESP8266
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: !secret ap_password

captive_portal:

i2c:
  sda: D2
  scl: D1
  scan: True
  id: bus_a
  
sensor:
  - platform: bme280
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
    pressure:
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"
    address: 0x77
    update_interval: 3min

#remote_receiver:
#  pin:
#    number: D3
#    inverted: true
#    mode: INPUT_PULLUP
#  dump: all
  
#remote_transmitter:
#  pin: D5
  # Infrared remotes use a 50% carrier signal
#  carrier_duty_percent: 50%
  
#switch:
#  - platform: template
#    name: Space Heater Power Button
#    turn_on_action:
#      - remote_transmitter.transmit_rc_switch_raw:
#          code: '11011000000'
#          protocol: 1
#  - platform: template
#    name: Space Heater Oscillate Button
#    turn_on_action:
#      - remote_transmitter.transmit_rc_switch_raw:
#          code: '11011000100'
#          protocol: 1